version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  fstest-core:
    build: ./core
    restart: always
    depends_on:
      - mongo
    network_mode: host

  fstest-webclient:
    build:
      context: webclient
    network_mode: host