version: '3'
services:
  mongo:
    image: mongo:4.1.13
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - /data/nextHuddle/local:/data/db
    ports:
      - 27018:27017

  fstest-core:
    build: core
    restart: always
    depends_on:
      - mongo
    network_mode: host

  fstest-webclient:
    build:
      context: webclient
    network_mode: host